-- 코드를 입력하세요
SELECT 
    B.TITLE, 
    B.BOARD_ID, 
    C.REPLY_ID, 
    C.WRITER_ID, 
    C.CONTENTS, 
    DATE_FORMAT(C.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD B
JOIN
    USED_GOODS_REPLY C
    ON B.BOARD_ID = C.BOARD_ID
WHERE
    B.CREATED_DATE LIKE '2022-10%'
ORDER BY
    C.CREATED_DATE,
    B.TITLE;